# Generated by Django 4.0.4 on 2022-05-28 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('edad', models.IntegerField()),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Posteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.TextField(max_length=100)),
                ('titulo', models.TextField(max_length=100)),
                ('categoria', models.TextField(max_length=100)),
                ('post', models.TextField(max_length=1000)),
                ('fecha_posteo', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
