# Generated by Django 4.0.4 on 2022-05-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=255)),
                ('domicilio', models.CharField(max_length=255)),
                ('sexo', models.CharField(max_length=255)),
            ],
        ),
    ]
